import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const sectionIds = {
  'Official Links': 'official',
  Wiki: 'wiki',
  Tools: 'tools',
  Development: 'development',
  Assets: 'assets',
  Miscellaneous: 'miscellaneous',
  Apps: 'apps',
  Bots: 'bots',
};

const zhSectionLabels = {
  official: '官方链接',
  wiki: 'Wiki',
  tools: '工具',
  development: '开发',
  assets: '素材',
  miscellaneous: '杂项',
  apps: '应用',
  bots: '机器人',
};

function parseReadme(markdown, locale) {
  const lines = markdown.split(/\r?\n/);
  const categories = [];
  let current = null;
  let inUnofficial = false;

  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+)$/);
    if (h2) {
      const title = h2[1].trim();
      inUnofficial = title === 'Unofficial Links' || title === '非官方链接';
      if (title === 'Official Links' || title === '官方链接') {
        current = {
          id: 'official',
          title,
          items: [],
        };
        categories.push(current);
      } else {
        current = null;
      }
      continue;
    }

    const h3 = line.match(/^###\s+(.+)$/);
    if (h3 && inUnofficial) {
      const title = h3[1].trim();
      const id =
        locale === 'en'
          ? sectionIds[title]
          : Object.entries(zhSectionLabels).find(([, label]) => label === title)?.[0];

      if (!id) {
        throw new Error(`Unknown ${locale} section: ${title}`);
      }

      current = {
        id,
        title,
        items: [],
      };
      categories.push(current);
      continue;
    }

    const item = line.match(/^-\s+\[([^\]]+)\]\(([^)]+)\)\s+-\s+(.+)$/);
    if (item && current) {
      current.items.push({
        name: item[1].trim(),
        url: item[2].trim(),
        description: item[3].trim(),
      });
    }
  }

  return categories;
}

function assertAligned(enCategories, zhCategories) {
  const enIds = enCategories.map((category) => category.id).join(',');
  const zhIds = zhCategories.map((category) => category.id).join(',');

  if (enIds !== zhIds) {
    throw new Error(`README category order mismatch: ${enIds} !== ${zhIds}`);
  }

  for (let categoryIndex = 0; categoryIndex < enCategories.length; categoryIndex += 1) {
    const enCategory = enCategories[categoryIndex];
    const zhCategory = zhCategories[categoryIndex];

    if (enCategory.items.length !== zhCategory.items.length) {
      throw new Error(
        `README item count mismatch in ${enCategory.id}: ${enCategory.items.length} !== ${zhCategory.items.length}`,
      );
    }

    for (let itemIndex = 0; itemIndex < enCategory.items.length; itemIndex += 1) {
      const enItem = enCategory.items[itemIndex];
      const zhItem = zhCategory.items[itemIndex];

      if (enItem.url !== zhItem.url) {
        throw new Error(
          `README URL mismatch in ${enCategory.id} item ${itemIndex + 1}: ${enItem.url} !== ${zhItem.url}`,
        );
      }
    }
  }
}

function toId(url, fallback) {
  const cleaned = url
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
    .replace(/\/$/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return cleaned || fallback;
}

const enMarkdown = await readFile(path.join(root, 'README.md'), 'utf8');
const zhMarkdown = await readFile(path.join(root, 'README.zh-CN.md'), 'utf8');

const enCategories = parseReadme(enMarkdown, 'en');
const zhCategories = parseReadme(zhMarkdown, 'zh-CN');
assertAligned(enCategories, zhCategories);

const categories = enCategories.map((enCategory, index) => ({
  id: enCategory.id,
  title: {
    en: enCategory.title,
    zhCN: zhCategories[index].title,
  },
}));

const resources = enCategories.flatMap((enCategory, categoryIndex) =>
  enCategory.items.map((enItem, itemIndex) => {
    const zhItem = zhCategories[categoryIndex].items[itemIndex];

    return {
      id: toId(enItem.url, `${enCategory.id}-${itemIndex + 1}`),
      categoryId: enCategory.id,
      name: {
        en: enItem.name,
        zhCN: zhItem.name,
      },
      url: enItem.url,
      description: {
        en: enItem.description,
        zhCN: zhItem.description,
      },
    };
  }),
);

const generated = `// This file is generated by scripts/generate-data.mjs. Do not edit by hand.

export type Locale = 'en' | 'zhCN';

export type Category = {
  id: string;
  title: Record<Locale, string>;
};

export type Resource = {
  id: string;
  categoryId: string;
  name: Record<Locale, string>;
  url: string;
  description: Record<Locale, string>;
};

export const categories = ${JSON.stringify(categories, null, 2)} satisfies Category[];

export const resources = ${JSON.stringify(resources, null, 2)} satisfies Resource[];
`;

await mkdir(path.join(root, 'src/data'), { recursive: true });
await writeFile(path.join(root, 'src/data/resources.generated.ts'), generated);

console.log(`Generated ${resources.length} resources across ${categories.length} categories.`);
